
paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["about.md"] # files to exclude
highlighter: true

# Build settings
markdown: kramdown

# Site settings
title: JingYu Liu
email: ljyhm88@gmail.com

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: JingYu Liu

description: Personal Website by Jingyu Liu.
author:
  name: JingYu Liu
  email: ljyhm88@gmail.com
  bio: PHD candidate


description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ljyhm.github.io" # the base hostname & protocol for your site


